workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable  # ← Ajouter cette ligne
      xcode: latest
    scripts:
      - name: Setup Flutter
        script: |
          flutter channel stable
          flutter upgrade
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - salmarabih4@gmail.com