workflows:
  ios-workflow:
    name: iOS IPA Build
    environment:
      xcode: latest
    scripts:
      - name: Build Unsigned IPA
        script: |
          # Configurer le bundle ID
          plutil -replace CFBundleIdentifier -string "com.groupelec.qrscanner" ios/Runner/Info.plist
          plutil -replace CFBundleDisplayName -string "Groupelec QR" ios/Runner/Info.plist
          
          # Build IPA sans signature complexe
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa