workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build iOS IPA
        script: |
          # D'abord configurer le bundle identifier
          plutil -replace CFBundleIdentifier -string "com.groupelec.qrscanner" ios/Runner/Info.plist
          plutil -replace CFBundleDisplayName -string "Groupelec QR" ios/Runner/Info.plist
          
          # Puis build avec code signing automatique
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - salmarabih4@gmail.com