workflows:
  ios-workflow:
    name: iOS IPA with Profile
    environment:
      xcode: latest
    scripts:
      - name: Build with Development Profile
        script: |
          # Configurer le bundle ID
          plutil -replace CFBundleIdentifier -string "com.groupelec.qrscanner" ios/Runner/Info.plist
          plutil -replace CFBundleDisplayName -string "Groupelec QR" ios/Runner/Info.plist
          
          # Créer un profil de développement basique
          /usr/libexec/PlistBuddy -c "Add :application-identifier string com.groupelec.qrscanner" embedded.mobileprovision 2>/dev/null || true
          
          # Build avec profil de développement
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa